name: umx
dependencies:
    - python=3.8
    - pip
    - pip:
        - pydub==0.25.1
        - librosa==0.9.2
        - openunmix==1.2.1
        - openvino==2022.2.0
        - --extra-index-url https://download.pytorch.org/whl/cu113
        - torch 
        - torchvision 
        - torchaudio 
        